name: Java CI with Maven and JUnit

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'

      - name: Build with Maven
        run: mvn clean package

      - name: Test with JUnit
        run: mvn test
